version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: lab_booking_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lab_booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: lab_booking_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab_booking_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: lab_booking_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  mobile:
    build: ./mobile
    container_name: lab_booking_mobile
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  postgres_data:
