server.port=${SERVER_PORT:8080}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.application.name=Lab Booking API

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Flyway - ENABLED
spring.flyway.enabled=true

# Security/App
app.jwt.secret=${APP_JWT_SECRET:VGhpc0lzQVNlY3JldEJhc2U2NEtleVNob3VsZExvbmdFbm91Z2g=}
app.jwt.expirationMillis=${APP_JWT_EXPIRATION_MILLIS:3600000}
app.google.clientId=${APP_GOOGLE_CLIENT_ID:}
app.google.androidClientId=${APP_GOOGLE_ANDROID_CLIENT_ID:}